### ISSUE TITLE
License

### ISSUE THREAD

**Issue by cygnus6** [vtsingaras/RavenPowerShell#1]
Hello Vyron,

I'd like to try your module, but I don't see any license attached to the code, only all rights reserved.
This means people may view your code, but not use it. Could you add something like a GPL or MIT license, or create your own?

**Comment by vtsingaras** [comment]
Apologies for the late response. Will take care of it ASAP.

**Comment by rriksma** [comment]
Thank you!
I just tested and it's working great.
